# Usamos la imagen oficial de Nginx como base
FROM nginx:latest

# Copiamos nuestro archivo index.html a la ruta donde Nginx busca la web
COPY index.html /usr/share/nginx/html/index.html

# Exponemos el puerto 80
EXPOSE 80